### ISSUE TITLE
running from within the mongo shell?

### ISSUE THREAD

**Issue by abrin** [variety/variety#131]
Pardon the basic question, but is there a way to load and run variety.js from within a mongo shell?  If so, could the documentation be updated?  Once you "load" the script, how would you call the function.

Separately, I get a weird error in Mongo 3.2.10:
```
Variety: A MongoDB Schema Analyzer
Version 1.5.0, released 14 May 2015
2016-12-14T09:09:19.636-0700 E QUERY    [thread1] Unknown Failure from JSInterpreter
2016-12-14T09:09:19.636-0700 E QUERY    [thread1] Error: error loading js file: /Users/abrin/Documents/workspace/nabo-prototype/src/main/resources/mongo/variety.js :
```

**Comment by JamesCropcho** [comment]
Thanks for getting in touch, Adam. And thank you for using Variety.

Regarding "[s]eparately," kindly create one precise ticket for each important item you're bringing to our attention.

I don't believe there is any way to load Variety into the MongoDB shell, no, if I'm understanding correctly. I mean, other than copy-pasting, but that's not what you likely prefer.

Tomáš / Eve ( @todvora @freeeve ), any thoughts?

**Comment by todvora** [comment]
Hi @abrin ,
This is related to https://github.com/variety/variety/issues/21 and https://github.com/variety/variety/issues/102. There is currently no support for this usage. You would need to wrap the whole function and provide all config attributes from outside. You can get some inspiration on https://github.com/gabrielelana/mongodb-shell-extensions if you decide to do it yourself. Please share with us your experience if you do so.

Regarding the error - is there any line number, expression or anything that could help to locate the exact cause please?

Thanks,
Tomas

**Comment by abrin** [comment]
@todvora thanks.  I don't have any context for the error, unfortunately. I think because of the namespaced / encapsulated functions it simply reports the following:

```
> load("/Users/abrin/Documents/workspace/nabo-prototype/src/main/resources/mongo/variety.js");
Variety: A MongoDB Schema Analyzer
Version 1.5.0, released 14 May 2015
2016-12-19T13:18:53.113-0700 E QUERY    [thread1] Unknown Failure from JSInterpreter
2016-12-19T13:18:53.113-0700 E QUERY    [thread1] Error: error loading js file: /Users/abrin/Documents/workspace/nabo-prototype/src/main/resources/mongo/variety.js :
@(shell):1:1
```

**Comment by todvora** [comment]
Hi @abrin,
Could you please remove the wrapping function (lines 12 and 385) from variety.js and test it once again? Maybe it will bring some more details. Right now I have no idea, what could it be. 

Our tests against MongoDB 3.2 are [passing](https://travis-ci.org/variety/variety/jobs/155183464) so far, but maybe your specific configuration, data collection or something like that...

Thanks again,
Tomas

**Comment by JamesCropcho** [comment]
Hey all, I'm going to close this for now to keep things clean. But by all means feel free to re-open and continue to make progress on this.

**Comment by abrin** [comment]
Just had time to do what was requested, although I've found ways around this issue using local tools.  What I get when I paste the value in is:

```
MongoDB shell version: 3.2.10
connecting to: test
> load("/Users/abrin/Documents/workspace/DataARC/src/main/resources/mongo/variety.js");
Variety: A MongoDB Schema Analyzer
Version 1.5.0, released 14 May 2015
2016-12-28T17:16:40.565-0700 E QUERY    [thread1] Unknown Failure from JSInterpreter
2016-12-28T17:16:40.565-0700 E QUERY    [thread1] Error: error loading js file: /Users/abrin/Documents/workspace/DataARC/src/main/resources/mongo/variety.js :
@(shell):1:1
```

**Comment by todvora** [comment]
Hi @abrin,
Now I get it. The error happens when you are trying to ```load``` variety.js directly from MongoDB shell. The exception you are seeing is actually [this one](https://github.com/variety/variety/blob/2f4d8151f3567382c63393f8fff0c4f83210d420/variety.js#L57), saying that there is no variable ```collection``` defined, which would tell Variety what to analyse. 

You can use Variety this way, if you provide it the collection name. Something like this should work:
```
var collection = 'users'; load('/some/path/to/variety.js');
```
Where the output will be similar to (shell with -quiet option enabled):

```
> var collection = 'users'; load('variety.js');
+--------------------------------------------------------------------+
| key                | types                | occurrences | percents |
| ------------------ | -------------------- | ----------- | -------- |
| _id                | ObjectId             |           5 |    100.0 |
| name               | String               |           5 |    100.0 |
| bio                | String               |           3 |     60.0 |
| birthday           | Date                 |           2 |     40.0 |
| pets               | String (1),Array (1) |           2 |     40.0 |
| someBinData        | BinData-old          |           1 |     20.0 |
| someWeirdLegacyKey | String               |           1 |     20.0 |
+--------------------------------------------------------------------+
true
```

The exception handling and logging is unfortunately not available in this mode. As the variety.js is loaded, is immediately evaluated and every exception thrown by Variety will be interpreted as exception during loading, effectively swallowing any exception message.

It would require some refactoring to be able to import Variety inside MongoDB shell and use it from there. Basically define a Variety function on ```DBCollection.prototype```, with additional Variety arguments passed in on a function invocation, do not execute the function during load... Something similar to [this usage](https://github.com/gabrielelana/mongodb-shell-extensions/blob/master/src/collection.js#L1). And then there is the compatibility with our script mode, which would need to be preserved. 

If you think it would be good functionality, I'll be more then glad to check your pull request, write tests or support you on your endeavour.

**Comment by JamesCropcho** [comment]
Hey all, I'm going to close this for now to keep things clean. But by all means feel free to re-open and continue to make progress on this.
