### ISSUE TITLE
Execution fail when document contains undefined values

### ISSUE THREAD

**Issue by gimmi** [variety/variety#136]
This is a quite strange situation, but Mongo3T show this:

![image](https://user-images.githubusercontent.com/6589/30113938-90a56932-9316-11e7-9577-5dea624bb2de.png)

And if i run Variety against this collection, i get this error:

```
> mongo.exe mydb --eval "var collection = 'users.settings';" variety.js

MongoDB shell version: 3.2.16-5-g8c49949
connecting to: mydb
Variety: A MongoDB Schema Analyzer
Version 1.5.0, released 14 May 2015
Using collection of "users.settings"
Using query of { }
Using limit of 88
Using maxDepth of 99
Using sort of { "_id" : -1 }
Using outputFormat of "ascii"
Using persistResults of false
Using resultsDatabase of "varietyResults"
Using resultsCollection of "users.settingsKeys"
Using resultsUser of null
Using resultsPass of null
Using logKeysContinuously of false
Using excludeSubkeys of [ ]
Using arrayEscape of "XX"
Using plugins of [ ]
2017-09-06T15:19:09.041+0200 E QUERY    [thread1] uncaught exception: varietyTypeOf() requires an argument
failed to load: variety.js
```

**Comment by JamesCropcho** [comment]
Thanks for letting us know, Mr. Gherardi. If not that's fine, but is there any way you could send over a collection which raises this uncaught exception?

James

**Comment by TimLudwinski** [comment]
`undefined` is a deprecated bson type.  You should change these values to `null` instead.

**Comment by gimmi** [comment]
Isn't Variety supposed to work on legacy/messy collections? If not what's the point of using it?

**Comment by todvora** [comment]
I will be more than glad to fix this issue, but I need a way how to insert `undefined` via the official node.js driver into a MongoDB database. Because now the `undefined` values are on-the-fly converted to `null` and I can't test them. 

If we don't find a way how to test it, we would have to blindly disable the check in `varietyTypeOf`, which isn't something I would like to do without proper testing. Let's keep that as a last resort option.

**Comment by gimmi** [comment]
Seems that [Node.js node-native-driver for MongoDB doesn't implement it at all.](http://devblog.me/wtf-mongo), but I'm able to insert `undefined` value using `mongo` CLI:

```
> mongo my_db --eval "db.getCollection('a_test_table').insert({ aNull: null, aUdef: undefined });"
```

**Comment by JamesCropcho** [comment]
I take it that inserting a `undefined` via the CLI just isn't really feasible for our purposes, right?

This sounds like a give-and-take in which the current configuration (the status quo) has superior net benefit to the alternative. This would mean we should keep things as they are.

Does anybody have other thoughts?

**Comment by gimmi** [comment]
Sorry but I don't get the point.

The reason I'm opening the issue is that Veriety fail when run against collection that _contains_ `undefined` values. I don't expect Variety to insert `undefined` values anywhere.

The CLI command has just been provided as a way to reproduce the problem, not to be included in Variety codebase, except for testing purpose.

BTW, variety is a tool designed to run with mongo CLI, why a CLI command is not "feasible"?

**Comment by JamesCropcho** [comment]
Okay, I am going to leave this open, so that an open source contributor can see this is a potential place to improve Variety. I don't consider it resolved, and so we may hope that someone may soon have the bandwidth to resolve this.

**Comment by gimmi** [comment]
Here is the 4 line long fix...

would be nice to have it integrated in the main repo.

**Comment by todvora** [comment]
Sorry for my delayed response, it's too busy time for me right now. I agree that this is in the scope of Variety and we should fix that. My only objection is that we should have it covered by tests. But this requires some CLI magic because it's not possible via the mongo client for the node.js. 

From my point of view - rather fixed without tests and add some tests later than keep it broken. What do others think? @JamesCropcho?

@gimmi: could you send a pull request with the change?

Thanks!

**Comment by gimmi** [comment]
Here is the PR #137
