### ISSUE TITLE
namespace must not be empty

### ISSUE THREAD

**Issue by pkgajulapalli** [variety/variety#145]
I'm using following command to analyize data
 
    mongo --host HOSTNAME:PORT DB_NAME --eval "var collection = 'COLLECTION'" variety.js

I'm getting following error

    2018-04-09T15:39:26.383+0530 E QUERY    [thread1] Error: listCollections failed: { "code" : -1, "ok" : 0, "$err" : "namespace must not be empty" } :
    _getErrorWithCode@src/mongo/shell/utils.js:25:13
    DB.prototype._getCollectionInfosCommand@src/mongo/shell/db.js:941:1
    DB.prototype.getCollectionInfos@src/mongo/shell/db.js:953:19
    DB.prototype.getCollectionNames@src/mongo/shell/db.js:964:16
    @variety.js:36:10
    @variety.js:35:5
    @variety.js:12:2
    failed to load: variety.js

I cloned the repo & did `npm install` before running this command.

**Comment by JamesCropcho** [comment]
Hello @pkgajulapalli, thanks for reporting this issue. Did you ever manage to figure it out?

@todvora and everyone else, any thoughts, perchance?

Interesting it appears that the only place on the internet where this error message appears verbatim is Apache OpenWhisk (https://github.com/apache/incubator-openwhisk). Weird, huh?

**Comment by pkgajulapalli** [comment]
@JamesCropcho, I couldn't figure out the reason for this.

**Comment by JamesCropcho** [comment]
@pkgajulapalli Are you able to get different or better behavior from Variety on any other collection or database within this same environment, or do all collections behave the same way in this environment, Praveen?

**Comment by pkgajulapalli** [comment]
@JamesCropcho I didn't test for other envs.

**Comment by JamesCropcho** [comment]
@pkgajulapalli No sweat. I believe what I'm asking, is perhaps simpler than that: are you able to run Variety on your development machine (or to get a different error message) when you try any other collections in the same database? A collection in another database?

**Comment by JamesCropcho** [comment]
@pkgajulapalli Thank you, Praveen.

So weird: is anyone able to reproduce this? Anyone have any insight?

**Comment by JamesCropcho** [comment]
Thanks again for reporting this, @pkgajulapalli.

We finally tracked this down and fixed it in #269. The root cause was not the `collection` variable itself; Variety was doing too much startup validation before it ever analyzed the requested collection. It called `listDatabases`, then tried to call `getCollectionNames()` / `listCollections` for every database MongoDB reported, including databases unrelated to the one being analyzed. In environments where one of those unrelated namespace lookups failed, Variety could die with `namespace must not be empty` before reaching the requested `DB_NAME` / `COLLECTION`.

We chose to fix that behavior directly. The merged change now scopes startup validation to the selected database: Variety still validates that the selected database and collection are usable, but it no longer enumerates collections for every other database on the server. We also added regression coverage for this exact class of failure and rebuilt the committed `variety.js` bundle.

Validation included the new adapter regression test, lint/typecheck/build verification, commit-hook checks, and a targeted MongoDB-backed Podman test run. Closing this as fixed by #269.
