### ISSUE TITLE
Use Variety in Java?

### ISSUE THREAD

**Issue by lumi257** [variety/variety#158]
Hello Tomas,
I would like to call variety in Java. Would you tell me what to do? I am not familiar with js.
Let me know.

Thank You,
lu

#49

**Comment by todvora** [comment]
Hello @lumi257,
The approach we used before was to start a new process from java, provide all command line options and retrieve the text output. You can see the integration here: https://github.com/variety/variety/tree/9895a4d5b4aee89dd2186cc444292748e4e93281/test/src/main/java/com/github/variety

The Variety.java class allows setting all the params and triggers the process for you. Usage may be seen here: https://github.com/variety/variety/blob/9895a4d5b4aee89dd2186cc444292748e4e93281/test/src/test/java/com/github/variety/test/BasicAnalysisTest.java

It maybe quite outdated since we migrated all tests to javascript many years ago.

Let me know if that works for you.

Regards,
Tomas

**Comment by lumi257** [comment]
> Hello @lumi257,
> The approach we used before was to start a new process from java, provide all command line options and retrieve the text output. You can see the integration here: https://github.com/variety/variety/tree/9895a4d5b4aee89dd2186cc444292748e4e93281/test/src/main/java/com/github/variety
> 
> The Variety.java class allows setting all the params and triggers the process for you. Usage may be seen here: https://github.com/variety/variety/blob/9895a4d5b4aee89dd2186cc444292748e4e93281/test/src/test/java/com/github/variety/test/BasicAnalysisTest.java
> 
> It may be quite outdated since we migrated all tests to javascript many years ago.
> 
> Let me know if that works for you.
> 
> Regards,
> Tomas

Hello Tomas,
Thanks for your reply. The Variety Java program works well.

Regards,
lumi

**Comment by todvora** [comment]
Glad I could help! 

Best regards,
Tomas
