### ISSUE TITLE
mongo vs mongosh

### ISSUE THREAD

**Issue by lucasoeth** [variety/variety#159]
Hey,

I'm trying to run the script with the new mongo shell (mongosh) and it seems to run into lots of errors like variables and functions not found. How can I get the old mongo shell or what would be the best way for me to get it working?

Thanks in advance

**Comment by JamesCropcho** [comment]
Hello Lucas,

Thank you for writing to Variety.

Hmm…I don't have any experience with MongoDB Shell (`mongosh`). Does anyone else here know what might be going on?

Also, Lucas, if you were to post the exact (if tactically redacted (if need be)) failing command(s) and their output, I think that could go a long way towards upping the odds of your getting some advice.

.
Regards,
James

**Comment by JamesCropcho** [comment]
Hi @lucasoeth,

Thanks for your patience. Since my earlier reply, the README has been updated to document `mongosh` as the primary shell, including the exact invocation pattern:

```sh
mongosh test --eval "var collection = 'users'" variety.js
```

The key is passing your variables via `--eval` *before* the script filename on the same command line. If you're still running into errors with that form, please feel free to reopen this issue and include the exact command you ran and the full error output — that'll give us something concrete to work from.

Closing for now as the general question is addressed in the README.
