### ISSUE TITLE
enable specifying results db and results collection name

### ISSUE THREAD

**Issue by viktorasm** [variety/variety#38]
it would be  a nice touch to be able to set resultsDB an resultsCollectionName via command line as well.

**Comment by Acetolyne** [comment]
Passing arguments to a js file is rather tricky. I found one way but then we have a depend of nodejs
with nodejs we could use variety at the command line with syntax 
nodejs variety.js ARGUMENTS

Another option is to make a shell script that simply passes the arguments as variables to the variety.js file. This meathod would leave out the dependancy of nodejs and would make the syntax

./variety arguments     instead of the syntax we use now   
mongo test --eval "var collection = 'users', limit = 1" variety.js

using this meathod we could pass arguments via the command line and have defaults if nothing is passed.
What does everyone else think about these meathods or does anyone have another meathod that would be better?

**Comment by JamesCropcho** [comment]
Hello Jon, thanks for thinking about this. I actually think that your comment is about another enhancement than what I intended in this ticket. This ticket is about specifying a custom database and/or collection for varietyResults.

But to touch on your points raised, I think the current method of passing command-line arguments is superior because of it's transparent mechanism and its "lightweight-ness," and because it is completely cross-platform and without a dependency on Node.js.

However, as always I am open to alternate possibilities, so let me know if you have further thoughts.

Thanks,
James
