### ISSUE TITLE
Using limit produces wrong percentage

### ISSUE THREAD

**Issue by Acetolyne** [variety/variety#76]
When you use limit = * the percentage seems to be based on the number you enter for the limit even when the results yield less results than the limit number. I believe percentage should not be based on the number you are looking for but rather the number which is returned.

**Comment by JamesCropcho** [comment]
Hello Jon,

Thanks for using Variety, and for getting in touch.

If the percentage returned were relative to the entire collection's size, it would have to be listed with some caveat, such as "Percentage (estimated)", because it really is an estimate- a prediction- rather than definitive in the way the percentage as given is currently definitive.

I could see the neccesary use of "estimated" or equivalent to be confusing in its own right.

For the above, I am inclined to think that the current way is superior. However, I remain open-minded to further thoughts you have, as well as seeing other people "plus-one" this thread, indicating additional interest.

Thank You,
James

**Comment by todvora** [comment]
Hi @Acetolyne, @JamesCropcho,
The issue is - when have 5 documents in your collection and limit set to 10, then in the results is correct occurence of 5, but incorrect percentage 50. The percentage computation is based on supplied number instead of real count of documents. 

I hope I fixed it in https://github.com/variety/variety/pull/79.

@Acetolyne: could you please verify, that the version from PR is working as expected?

Thank you both!
Tomas

**Comment by Acetolyne** [comment]
@todvora Thanks I think I did not communicate the problem well #79 seems to fix the problem
