### ISSUE TITLE
Output can be very hard to read when wider than the screen

### ISSUE THREAD

**Issue by alexbfree** [variety/variety#98]
I have tried this on some of our large databases, and am finding that it produces output that is wider than the screen, making the table very hard to read... 
Could this perhaps be addressed by adding support for HTML output instead of an ASCII table? Then the output could be viewed in a browser and scrolled. 
(I am on Mac OS X, not sure if Windows/Linux terminals handle the scrolling better)

EDIT: [Here is some example output](https://gist.github.com/alexbfree/db56aceb3587ba7b0fbe)...  viewable fine on the Gist, but not when it comes out in the console or even when viewed in Sublime Text 2.

**Comment by JamesCropcho** [comment]
Huh. Thanks for sharing, Alex.

Well, we do have LaTeX, JSON and CSV support via plugins: http://plugins.varietyjs.org/

It could be easy to render HTML from dynamically-generated JSON?

I have mixed thoughts about rendering to HTML, because it seems like it would be an onerous workflow, locally, and not useful for production because the HTML wouldn't be stylized, have a company logo, etc.

Thoughts, Alex? Anybody else?


—James

**Comment by alexbfree** [comment]
Thanks James for the response!

For me, variety is not something I use in production - it's just a tool for better understanding the legacy databases I have to work with. As such, what I really want as a user is just a quick, easy to digest view of what's in the database. Anything else than a legible text or HTML output is just extra work.

I certainly wouldn't care about logos etc - even if I did, it would be trivial to modify the HTML to add that.

**Comment by JamesCropcho** [comment]
Alex,

It's not actively developed nor maintained, but you might check out MightyMightyMongo (https://github.com/JacobGH111/mightymightymongo), either to use or for inspiration.

Otherwise, I'd invite you to make a plugin (you've already seen the repository) which could either be specific to you, or generalized for Open Source release. Either way. But I think that'd be a fine approach.

Another, possibly better approach would be to serve the JSON output via a web service (oh, I should mention we have a Java wrapper), and then built a table, or what have you, browser-side.

I'm closing for now, but feel free to re-open.

Godspeed, Alex!


—J
